Traceback (most recent call last):
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/creative/miniconda3/envs/jupyter-book/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
net.layer1.weight.data = torch.Tensor(np.random.normal(size=(1,2), scale=0.01, loc=0))
net.layer1.bias.data = torch.Tensor([0])
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_6009/2886098504.py[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mnet[0m[0;34m.[0m[0mlayer1[0m[0;34m.[0m[0mweight[0m[0;34m.[0m[0mdata[0m [0;34m=[0m [0mtorch[0m[0;34m.[0m[0mTensor[0m[0;34m([0m[0mnp[0m[0;34m.[0m[0mrandom[0m[0;34m.[0m[0mnormal[0m[0;34m([0m[0msize[0m[0;34m=[0m[0;34m([0m[0;36m1[0m[0;34m,[0m[0;36m2[0m[0;34m)[0m[0;34m,[0m [0mscale[0m[0;34m=[0m[0;36m0.01[0m[0;34m,[0m [0mloc[0m[0;34m=[0m[0;36m0[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mnet[0m[0;34m.[0m[0mlayer1[0m[0;34m.[0m[0mbias[0m[0;34m.[0m[0mdata[0m [0;34m=[0m [0mtorch[0m[0;34m.[0m[0mTensor[0m[0;34m([0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'net' is not defined
NameError: name 'net' is not defined

